name: Main import action

on:
    push:
      branches:
        - "*"

jobs:
  docker:
    uses: Gravitate-Health/reusable-workflows/.github/workflows/main.yml@main
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}